version: '3.8'

services:
  front:
    container_name: 'lille-gophers-website'
    image: node:alpine
    volumes:
      - '.:/app'
    working_dir: /app
    entrypoint: ['./entrypoint.sh', 'npm', 'run', 'dev']
